source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!


target 'iTax Calc' do
	pod 'M13ProgressSuite'
	pod 'DateTools'
	pod 'XYPieChart'
	pod 'JVFloatLabeledTextField'
	pod 'ionicons'
end